// static-react/src/pages/dashboard-console/fleet-list.tsx
import { useI18n } from '@/i18n'
import { formatTime } from '@/lib/format'
import type { DashboardFleetItem } from '@/types/api/dashboard'
import { cn } from '@/lib/utils'

interface DashboardFleetListProps {
  fleets: DashboardFleetItem[]
  className?: string
}

function resolveImportanceKey(importance: string | undefined): string | null {
  if (!importance) {
    return null
  }

  const known = new Set(['strat_op', 'cta', 'other'])
  return known.has(importance) ? importance : null
}

export function DashboardFleetList({ fleets, className }: DashboardFleetListProps) {
  const { t } = useI18n()

  return (
    <section className={cn('flex h-128 flex-col rounded-lg border bg-card p-5', className)}>
      <header className="mb-2 flex items-center justify-between gap-2">
        <div>
          <h4 className="text-sm font-semibold">{t('dashboardConsole.fleetList.title')}</h4>
          <p className="text-xs text-muted-foreground">
            {t('dashboardConsole.fleetList.records', { count: fleets.length })}
          </p>
        </div>
      </header>

      <div className="mt-2 flex-1 overflow-auto">
        {fleets.length === 0 ? (
          <div className="flex h-full items-center justify-center text-sm text-muted-foreground">
            {t('dashboardConsole.fleetList.empty')}
          </div>
        ) : (
          <ul className="divide-y divide-border">
            {fleets.map((item, index) => {
              const importanceKey = resolveImportanceKey(item.importance)
              return (
                <li
                  key={`${item.source}-${item.id}-${index}`}
                  className="flex items-center gap-3 py-3 text-sm"
                >
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <span
                        className={cn(
                          'inline-flex items-center rounded border px-1.5 py-0.5 text-[10px] font-medium uppercase',
                          item.source === 'alliance'
                            ? 'border-amber-500/40 text-amber-600 dark:text-amber-400'
                            : 'border-primary/40 text-primary'
                        )}
                      >
                        {item.source === 'alliance'
                          ? t('dashboardConsole.fleetList.source.alliance')
                          : t('dashboardConsole.fleetList.source.internal')}
                      </span>
                      <span className="truncate font-medium">{item.title}</span>
                    </div>
                    <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground">
                      <span>{formatTime(item.start_at)}</span>
                      {item.character_name ? <span>{item.character_name}</span> : null}
                      {item.ship_type_name ? <span>{item.ship_type_name}</span> : null}
                      {importanceKey ? (
                        <span>{t(`dashboardConsole.fleetList.importance.${importanceKey}`)}</span>
                      ) : null}
                    </div>
                  </div>
                  <div className="shrink-0 text-right">
                    <span className="font-medium text-primary">{item.pap_count}</span>
                    <span className="ml-0.5 text-xs text-muted-foreground">{t('common.pap')}</span>
                  </div>
                </li>
              )
            })}
          </ul>
        )}
      </div>
    </section>
  )
}

// static/src/views/dashboard/console/modules/fleet-list.vue
<template>
  <div class="art-card h-128 p-5 mb-5 max-sm:mb-4">
    <div class="art-card-header">
      <div class="title">
        <h4>{{ $t('dashboardConsole.fleetList.title') }}</h4>
        <p>{{ $t('dashboardConsole.fleetList.records', { count: fleets.length }) }}</p>
      </div>
    </div>
    <div class="h-[calc(100%-40px)] overflow-auto mt-2">
      <ElScrollbar>
        <div v-if="fleets.length === 0" class="flex-cc h-full text-g-500 text-sm">
          {{ $t('dashboardConsole.fleetList.empty') }}
        </div>
        <div
          v-for="(item, index) in fleets"
          :key="`${item.source}-${item.id}-${index}`"
          class="flex-cb py-3 border-b border-g-300 text-sm last:border-b-0"
        >
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2">
              <ElTag
                :type="item.source === 'alliance' ? 'warning' : 'primary'"
                size="small"
                effect="plain"
              >
                {{
                  item.source === 'alliance'
                    ? $t('dashboardConsole.fleetList.source.alliance')
                    : $t('dashboardConsole.fleetList.source.internal')
                }}
              </ElTag>
              <span class="text-g-800 font-medium truncate">{{ item.title }}</span>
            </div>
            <div class="flex items-center gap-3 mt-1 text-xs text-g-500">
              <span>{{ formatTime(item.start_at) }}</span>
              <span v-if="item.character_name">{{ item.character_name }}</span>
              <span v-if="item.ship_type_name">{{ item.ship_type_name }}</span>
              <span v-if="item.importance" class="capitalize">{{
                importanceLabel(item.importance)
              }}</span>
            </div>
          </div>
          <div class="text-right ml-3 shrink-0">
            <span class="text-theme font-medium">{{ item.pap_count }}</span>
            <span class="text-xs text-g-500 ml-0.5">PAP</span>
          </div>
        </div>
      </ElScrollbar>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { useI18n } from 'vue-i18n'
  import { formatTime } from '@utils/common'

  const { t } = useI18n()
  defineProps<{
    fleets: Api.Dashboard.FleetItem[]
  }>()

  const importanceLabel = (importance: string): string => {
    return t(`fleet.importance.${importance}`)
  }
</script>
