// static-react/src/pages/dashboard-console/srp-list.tsx
import { useI18n } from '@/i18n'
import { formatIskSmart } from '@/lib/isk'
import { formatTime } from '@/lib/format'
import type { DashboardSrpItem } from '@/types/api/dashboard'
import { cn } from '@/lib/utils'

interface DashboardSrpListProps {
  list: DashboardSrpItem[]
  className?: string
}

type StatusTone = 'primary' | 'success' | 'warning' | 'danger' | 'info'

const REVIEW_STATUS_TONE: Record<string, StatusTone> = {
  submitted: 'warning',
  approved: 'success',
  rejected: 'danger',
}

const PAYOUT_STATUS_TONE: Record<string, StatusTone> = {
  notpaid: 'info',
  paid: 'success',
}

const REVIEW_STATUS_KEYS = new Set(['submitted', 'approved', 'rejected'])
const PAYOUT_STATUS_KEYS = new Set(['notpaid', 'paid'])

function StatusBadge({
  label,
  tone,
}: {
  label: string
  tone: StatusTone
}) {
  return (
    <span
      className={cn(
        'inline-flex items-center rounded border px-1.5 py-0.5 text-[10px] font-medium uppercase',
        toneClass(tone)
      )}
    >
      {label}
    </span>
  )
}

function toneClass(tone: StatusTone): string {
  switch (tone) {
    case 'primary':
      return 'border-primary/40 text-primary'
    case 'success':
      return 'border-success/40 text-success-foreground'
    case 'warning':
      return 'border-amber-500/40 text-amber-600 dark:text-amber-400'
    case 'danger':
      return 'border-destructive/40 text-destructive'
    case 'info':
    default:
      return 'border-muted-foreground/30 text-muted-foreground'
  }
}

export function DashboardSrpList({ list, className }: DashboardSrpListProps) {
  const { t } = useI18n()

  const resolveReviewLabel = (status: string): string =>
    REVIEW_STATUS_KEYS.has(status)
      ? t(`dashboardConsole.srpList.reviewStatus.${status}`)
      : status

  const resolvePayoutLabel = (status: string): string =>
    PAYOUT_STATUS_KEYS.has(status)
      ? t(`dashboardConsole.srpList.payoutStatus.${status}`)
      : status

  return (
    <section className={cn('rounded-lg border bg-card p-5', className)}>
      <header className="mb-4 flex items-center justify-between gap-2">
        <div>
          <h4 className="text-sm font-semibold">{t('dashboardConsole.srpList.title')}</h4>
          <p className="text-xs text-muted-foreground">
            {t('dashboardConsole.srpList.recentCount', { count: list.length })}
          </p>
        </div>
      </header>

      {list.length === 0 ? (
        <div className="flex h-30 items-center justify-center text-sm text-muted-foreground">
          {t('dashboardConsole.srpList.empty')}
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full min-w-[860px] border-collapse text-sm">
            <thead>
              <tr className="border-b border-border text-left text-xs text-muted-foreground">
                <th className="px-3 py-2 font-medium">
                  {t('dashboardConsole.srpList.columns.character')}
                </th>
                <th className="px-3 py-2 font-medium">
                  {t('dashboardConsole.srpList.columns.ship')}
                </th>
                <th className="px-3 py-2 font-medium">
                  {t('dashboardConsole.srpList.columns.system')}
                </th>
                <th className="px-3 py-2 font-medium">
                  {t('dashboardConsole.srpList.lossTime')}
                </th>
                <th className="px-3 py-2 text-right font-medium">
                  {t('dashboardConsole.srpList.recommendedAmount')}
                </th>
                <th className="px-3 py-2 text-right font-medium">
                  {t('dashboardConsole.srpList.finalAmount')}
                </th>
                <th className="px-3 py-2 text-center font-medium">
                  {t('dashboardConsole.srpList.columns.reviewStatus')}
                </th>
                <th className="px-3 py-2 text-center font-medium">
                  {t('dashboardConsole.srpList.columns.payoutStatus')}
                </th>
              </tr>
            </thead>
            <tbody>
              {list.map((row) => {
                const reviewTone = REVIEW_STATUS_TONE[row.review_status] ?? 'info'
                const payoutTone = PAYOUT_STATUS_TONE[row.payout_status] ?? 'info'
                return (
                  <tr key={row.id} className="border-b border-border last:border-b-0">
                    <td className="px-3 py-2">{row.character_name}</td>
                    <td className="px-3 py-2">{row.ship_name}</td>
                    <td className="px-3 py-2">{row.solar_system_name}</td>
                    <td className="px-3 py-2">{formatTime(row.killmail_time)}</td>
                    <td className="px-3 py-2 text-right text-muted-foreground">
                      {formatIskSmart(row.recommended_amount)}
                    </td>
                    <td className="px-3 py-2 text-right font-medium">
                      {formatIskSmart(row.final_amount)}
                    </td>
                    <td className="px-3 py-2 text-center">
                      <StatusBadge
                        label={resolveReviewLabel(row.review_status)}
                        tone={reviewTone}
                      />
                    </td>
                    <td className="px-3 py-2 text-center">
                      <StatusBadge
                        label={resolvePayoutLabel(row.payout_status)}
                        tone={payoutTone}
                      />
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      )}
    </section>
  )
}

// static/src/views/dashboard/console/modules/srp-list.vue
<template>
  <div class="art-card p-5 mb-5 max-sm:mb-4">
    <div class="art-card-header mb-4">
      <div class="title">
        <h4>{{ $t('dashboardConsole.srpList.title') }}</h4>
        <p>{{ $t('dashboardConsole.srpList.recentCount', { count: list.length }) }}</p>
      </div>
    </div>
    <div v-if="list.length === 0" class="flex-cc h-30 text-g-500 text-sm">
      {{ $t('dashboardConsole.srpList.empty') }}
    </div>
    <ArtTable
      v-else
      :data="list"
      size="large"
      :border="false"
      :stripe="false"
      :header-cell-style="{ background: 'transparent' }"
    >
      <template #default>
        <ElTableColumn
          :label="$t('srp.apply.columns.character')"
          prop="character_name"
          min-width="120"
        />
        <ElTableColumn :label="$t('srp.apply.columns.ship')" prop="ship_name" min-width="140" />
        <ElTableColumn
          :label="$t('srp.apply.columns.system')"
          prop="solar_system_name"
          min-width="120"
        />
        <ElTableColumn :label="$t('dashboardConsole.srpList.lossTime')" min-width="160">
          <template #default="{ row }">
            {{ formatTime(row.killmail_time) }}
          </template>
        </ElTableColumn>
        <ElTableColumn
          :label="$t('dashboardConsole.srpList.recommendedAmount')"
          min-width="120"
          align="right"
        >
          <template #default="{ row }">
            <span class="text-g-700">{{ formatISK(row.recommended_amount) }}</span>
          </template>
        </ElTableColumn>
        <ElTableColumn
          :label="$t('dashboardConsole.srpList.finalAmount')"
          min-width="120"
          align="right"
        >
          <template #default="{ row }">
            <span class="font-medium">{{ formatISK(row.final_amount) }}</span>
          </template>
        </ElTableColumn>
        <ElTableColumn :label="$t('srp.apply.columns.reviewStatus')" min-width="90" align="center">
          <template #default="{ row }">
            <ElTag :type="reviewStatusType(row.review_status)" size="small" effect="plain">
              {{ reviewStatusLabel(row.review_status) }}
            </ElTag>
          </template>
        </ElTableColumn>
        <ElTableColumn :label="$t('srp.apply.columns.payoutStatus')" min-width="90" align="center">
          <template #default="{ row }">
            <ElTag :type="payoutStatusType(row.payout_status)" size="small" effect="plain">
              {{ payoutStatusLabel(row.payout_status) }}
            </ElTag>
          </template>
        </ElTableColumn>
      </template>
    </ArtTable>
  </div>
</template>

<script setup lang="ts">
  import { useI18n } from 'vue-i18n'
  import { formatTime } from '@utils/common'

  const { t } = useI18n()
  defineProps<{
    list: Api.Dashboard.SrpItem[]
  }>()

  const formatISK = (amount: number): string => {
    if (!amount) return '0'
    return amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  }

  const reviewStatusLabel = (status: string): string => {
    const map: Record<string, string> = {
      submitted: t('srp.status.submitted'),
      approved: t('srp.status.approved'),
      rejected: t('srp.status.rejected')
    }
    return map[status] ?? status
  }

  const reviewStatusType = (
    status: string
  ): 'primary' | 'success' | 'warning' | 'danger' | 'info' => {
    const map: Record<string, 'primary' | 'success' | 'warning' | 'danger' | 'info'> = {
      submitted: 'warning',
      approved: 'success',
      rejected: 'danger'
    }
    return map[status] ?? 'info'
  }

  const payoutStatusLabel = (status: string): string => {
    const map: Record<string, string> = {
      notpaid: t('srp.status.notpaid'),
      paid: t('srp.status.paid')
    }
    return map[status] ?? status
  }

  const payoutStatusType = (
    status: string
  ): 'primary' | 'success' | 'warning' | 'danger' | 'info' => {
    const map: Record<string, 'primary' | 'success' | 'warning' | 'danger' | 'info'> = {
      notpaid: 'info',
      paid: 'success'
    }
    return map[status] ?? 'info'
  }
</script>
