// static-react/src/components/fuxi-hall-member-card.tsx
import { buildEveCharacterPortraitUrl } from '@/lib/eve-image'
import { useI18n } from '@/i18n'
import type { FuxiHallCard } from '@/types/api/fuxi-hall'

export function FuxiHallMemberCard({
  card,
  showStats = false,
}: {
  card: FuxiHallCard
  showStats?: boolean
}) {
  const { t } = useI18n()
  const avatarClass =
    card.avatar_shape === 'circle'
      ? 'rounded-full'
      : card.avatar_shape === 'rounded'
        ? 'rounded-xl'
        : 'rounded-md'
  const style = { borderColor: `${card.accent_color}50`, fontSize: `${card.font_scale}px` }
  return (
    <article className="min-w-0 rounded-2xl border bg-card" style={style}>
      <div className="p-4">
        <div className="flex gap-3">
          {card.main_character_id > 0 ? (
            <img
              className={`h-[72px] w-[72px] shrink-0 border-2 object-cover ${avatarClass}`}
              style={{ borderColor: `${card.accent_color}80` }}
              src={buildEveCharacterPortraitUrl(card.main_character_id, 256)}
              alt={card.nickname}
            />
          ) : null}
          <div className="min-w-0">
            <h3 className="font-semibold" style={{ fontSize: `${card.font_scale + 3}px` }}>
              {card.nickname}
            </h3>
            <p className="mt-1 italic text-muted-foreground">{card.main_character_name}</p>
            <div className="mt-2 flex flex-wrap gap-1">
              {card.title_tags.map((tag) => (
                <span
                  key={`${card.id}-${tag}`}
                  className="rounded-full border px-2 py-0.5 text-xs"
                  style={{ color: card.accent_color, borderColor: card.accent_color }}
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>
        </div>
        {card.description_html ? (
          <div
            className="mt-3 leading-relaxed text-muted-foreground [&_a]:text-primary [&_a]:underline [&_img]:max-w-full"
            dangerouslySetInnerHTML={{ __html: card.description_html }}
          />
        ) : null}
        {showStats &&
        ((card.fleet_led_count ?? 0) > 0 || (card.welfare_delivery_count ?? 0) > 0) ? (
          <div className="mt-3 space-y-1 text-sm">
            {(card.fleet_led_count ?? 0) > 0 ? (
              <p>
                {t('fuxiHall.public.fleetLedCount')}: {card.fleet_led_count}
              </p>
            ) : null}
            {(card.welfare_delivery_count ?? 0) > 0 ? (
              <p>
                {t('fuxiHall.public.welfareDeliveryCount')}: {card.welfare_delivery_count}
              </p>
            ) : null}
          </div>
        ) : null}
      </div>
    </article>
  )
}

// static/src/views/fuxi-hall/components/FuxiHallMemberCard.vue
<template>
  <article class="fuxi-hall-member-card" :style="cardStyle">
    <div class="fuxi-hall-member-card__body">
      <div class="fuxi-hall-member-card__meta">
        <img
          v-if="card.main_character_id > 0"
          class="fuxi-hall-member-card__avatar"
          :class="`is-${card.avatar_shape}`"
          :src="buildEveCharacterPortraitUrl(card.main_character_id, 256)"
          :alt="card.nickname"
        />
        <div class="fuxi-hall-member-card__identity">
          <h3>{{ card.nickname }}</h3>
          <p class="fuxi-hall-member-card__main-name">{{ card.main_character_name }}</p>
          <div v-if="card.title_tags.length > 0" class="fuxi-hall-member-card__title-tags">
            <ElTag
              v-for="tag in card.title_tags"
              :key="`${card.id}-${tag}`"
              size="small"
              effect="plain"
              round
              :style="tagStyle"
            >
              {{ tag }}
            </ElTag>
          </div>
        </div>
      </div>
      <div class="fuxi-hall-member-card__description" v-html="card.description_html" />
      <div
        v-if="
          showStats && ((card.fleet_led_count ?? 0) > 0 || (card.welfare_delivery_count ?? 0) > 0)
        "
        class="fuxi-hall-member-card__stats"
      >
        <p v-if="(card.fleet_led_count ?? 0) > 0">
          {{ t('fuxiHall.public.fleetLedCount') }}：{{ card.fleet_led_count }}
        </p>
        <p v-if="(card.welfare_delivery_count ?? 0) > 0"
          >{{ t('fuxiHall.public.welfareDeliveryCount') }}：{{ card.welfare_delivery_count }}</p
        >
      </div>
    </div>
  </article>
</template>

<script setup lang="ts">
  import { computed } from 'vue'
  import { useI18n } from 'vue-i18n'

  import { buildEveCharacterPortraitUrl } from '@/utils/eve-image'

  const props = defineProps<{
    card: Api.FuxiHall.Card
    showStats?: boolean
  }>()
  const { t } = useI18n()

  const cardStyle = computed(() => ({
    '--accent-color': props.card.accent_color,
    '--member-font-size': `${props.card.font_scale}px`
  }))

  const tagStyle = computed(() => ({
    color: props.card.accent_color,
    borderColor: props.card.accent_color,
    backgroundColor: 'transparent'
  }))
</script>

<style scoped>
  .fuxi-hall-member-card {
    border: 1px solid color-mix(in srgb, var(--accent-color), transparent 76%);
    border-radius: 16px;
    background: var(--el-bg-color);
    min-width: 0;
  }

  .fuxi-hall-member-card__body {
    padding: 14px;
    color: var(--el-text-color-regular);
    font-size: var(--member-font-size);
  }

  .fuxi-hall-member-card__meta {
    display: flex;
    align-items: flex-start;
    gap: 12px;
  }

  .fuxi-hall-member-card__avatar {
    width: 72px;
    height: 72px;
    object-fit: cover;
    flex-shrink: 0;
    border: 2px solid color-mix(in srgb, var(--accent-color), transparent 62%);
    display: block;
  }

  .fuxi-hall-member-card__avatar.is-circle {
    border-radius: 999px;
  }

  .fuxi-hall-member-card__avatar.is-rounded {
    border-radius: 12px;
  }

  .fuxi-hall-member-card__avatar.is-square {
    border-radius: 8px;
  }

  .fuxi-hall-member-card__identity h3 {
    margin: 0;
    color: var(--el-text-color-primary);
    font-size: calc(var(--member-font-size) + 3px);
  }

  .fuxi-hall-member-card__main-name {
    margin: 4px 0 0;
    color: var(--el-text-color-regular);
    font-style: italic;
  }

  .fuxi-hall-member-card__title-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
    margin-top: 6px;
  }

  .fuxi-hall-member-card__description {
    margin-top: 8px;
    color: var(--el-text-color-secondary);
    line-height: 1.6;
    overflow-wrap: anywhere;
  }

  .fuxi-hall-member-card__stats {
    margin-top: 10px;
    color: var(--el-text-color-regular);
    font-size: calc(var(--member-font-size) - 1px);
    line-height: 1.5;
  }

  .fuxi-hall-member-card__stats p {
    margin: 0;
  }
</style>
